spring.datasource.url=jdbc:postgresql://localhost:5432/zenbank_db
spring.datasource.username=yann
spring.datasource.password=bankpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Désactiver Spring Security temporairement pour nos premiers tests d'API
spring.security.user.name=admin
spring.security.user.password=admin